name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Check out AudioKitEX
        uses: actions/checkout@v4
      - name: Test AudioKitEX
        run: swift test -c release

  # Send notification to Discord on failure.
  send_notification:
    name: Send Notification
    uses: AudioKit/ci/.github/workflows/send_notification.yml@main
    needs: [swift_test]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    secrets: inherit
